/* AUTO-GENERATED from the texts list — default texts used when a field is empty in Sanity. */

export const DEFAULT_TEXTS = {
  siteName: "Swipe Québec",
  location: "Québec",
  country: "Canada",
  htmlLang: "fr-CA",
  ogLocale: "fr_CA",
  dateLocale: "fr-CA",
  ageText: "{age} ans",
  breadcrumbHome: "Accueil",
  seoTitleTemplate: "{page} | {siteName}",
  seoHomeTitle: "Swipe Québec – Glissez, craquez, discutez",
  seoHomeDescription: "Swipez les profils de femmes célibataires du Québec : à droite pour voir son profil, vers le haut pour discuter avec elle. Tous les profils sont aussi dans la page Annonces.",
  seoKeywords: "rencontre québec, rencontres québec, célibataires québec, site de rencontre québec, rencontre sérieuse québec",
  seoAnnoncesTitle: "Toutes les annonces – Célibataires au Québec",
  seoAnnoncesDescription: "Parcourez des milliers de profils vérifiés partout au Québec.",
  seoSearchTitle: "Recherche « {q} » – Annonces Québec",
  seoSearchDescription: "Résultats pour « {q} » parmi les célibataires du Québec.",
  seoCategoriesTitle: "Types de rencontres au Québec – Catégories",
  seoCategoriesDescription: "Choisissez votre type de rencontre au Québec sur {siteName} : relation sérieuse, aventure, amitié et plus.",
  seoCategoryTitle: "{category} au Québec – Rencontres {emoji}",
  seoCategoryDescription: "Trouvez des profils « {category} » partout au Québec.",
  seoProfileTitle: "{name}, {age} ans – Rencontre au {location}",
  seoProfileDescription: "Découvrez {name} sur {siteName}.",
  seoBlogTitle: "Blog – Conseils rencontres au Québec",
  seoBlogDescription: "Articles et conseils pour réussir vos rencontres au Québec. Trucs, astuces et guides pour célibataires.",
  seoTagsTitle: "Tags : rencontres selon vos préférences",
  seoTagsDescription: "Explorez les différentes catégories et trouvez le type de rencontre qui vous correspond.",
  seoLegalDescription: "Divulgation d'affiliation, avertissement, politique de confidentialité et conditions d'utilisation de {siteName}.",
  seoConditionsDescription: "Conditions générales d'utilisation du site {siteName}. Règles d'accès, responsabilités et informations sur notre modèle d'affiliation.",
  seoPrivacyDescription: "Comment {siteName} collecte, utilise et protège vos données personnelles.",
  navHome: "Accueil",
  navAnnonces: "Annonces",
  navCategories: "Catégories",
  navBlog: "Blog",
  searchPlaceholder: "Rechercher un profil, un intérêt...",
  searchPlaceholderMobile: "🔍 Rechercher un profil...",
  onlineText: "{count} en ligne",
  joinButton: "Rejoindre",
  heroTitle: "Trouvez votre",
  heroHighlight: "Âme Sœur ou votre Plan Cul au Québec",
  heroSubtitle: "Glissez à droite pour voir son profil, vers le haut pour discuter avec elle.",
  allProfilesNote: "📋 Tous les profils ({count}) sont dans la page Annonces, avec filtres et recherche.",
  allProfilesButton: "Voir tous les profils →",
  homeEmpty: "Aucun profil disponible pour le moment.",
  swipeStampLike: "VOIR PROFIL",
  swipeStampNope: "PASSER",
  swipeStampUp: "💬 DISCUTER",
  swipeHelpLeft: "← Passer",
  swipeHelpUp: "↑ Discuter",
  swipeHelpRight: "Profil →",
  swipeBtnNope: "Passer",
  swipeBtnUp: "Discuter",
  swipeBtnLike: "Voir profil",
  swipeOnline: "● En ligne",
  swipeVerified: "✓ Vérifiée",
  swipeEndTitle: "Vous avez vu tous les profils du moment!",
  swipeEndText: "Retrouvez les {count} profils dans la page Annonces, ou recommencez.",
  swipeEndButton: "❤ Voir tous les profils",
  swipeRestart: "↺ Recommencer",
  annoncesTitle: "Toutes les annonces",
  annoncesAll: "Toutes ({count})",
  countOne: "{count} profil trouvé",
  countMany: "{count} profils trouvés",
  searchFor: "pour « {q} »",
  annoncesEmpty: "Aucun profil trouvé.",
  annoncesEmptyLink: "Voir toutes les annonces",
  categoriesBreadcrumb: "Catégories",
  categoriesTitle: "Rencontres selon vos préférences",
  categoriesSubtitle: "Trouvez la catégorie parfaite pour vous.",
  categoryProfiles: "{count} profils",
  categoryEmpty: "Aucun profil dans cette catégorie pour le moment.",
  categoryOthers: "Autres catégories",
  categoryAbout: "À propos de {category}",
  cardOnline: "En ligne",
  profileRelated: "Profils similaires",
  popupButton: "🔒 Continuer sur la plateforme sécurisée",
  popupTitle: "🔐 Accès Privé Sécurisé",
  popupText: "{name} vous attend au {location}.",
  popupText2: "Confirmez votre email pour accéder immédiatement.",
  popupPlaceholder: "Entrez votre email privé...",
  popupSubmit: "🔥 Accéder maintenant",
  popupLoading: "Vérification en cours...",
  popupCheck1: "✔ 100% confidentiel",
  popupCheck2: "✔ Aucun spam",
  popupCheck3: "✔ Accès immédiat",
  popupConsent: "En continuant, vous confirmez avoir 18 ans ou plus et acceptez notre",
  popupConsentLink: "politique de confidentialité",
  popupErrorEmail: "Veuillez entrer un email valide.",
  popupErrorLink: "Le lien partenaire n'est pas encore configuré.",
  blogBreadcrumb: "Blog",
  blogTitle: "Blog & Conseils",
  blogSubtitle: "Trucs, astuces et guides pour réussir vos rencontres au Québec.",
  blogEmpty: "Aucun article publié pour le moment.",
  blogReadMore: "Lire l'article →",
  blogBack: "← Retour au blog",
  tagsTitle: "Tags : rencontres selon vos préférences",
  tagsSubtitle: "Trouvez une personne qui offre exactement ce que vous cherchez.",
  tagsButton: "Voir tous les profils →",
  footerDescription: "Annuaire de rencontres partenaires partout au Québec. Site d'affiliation pour adultes 18+.",
  footerExploreTitle: "Explorer",
  footerLegalTitle: "Informations légales",
  footerLinkAnnonces: "❤ Annonces",
  footerLinkCategories: "💝 Catégories",
  footerLinkBlog: "📝 Blog",
  footerLinkTags: "🏷️ Tags",
  footerLinkLegal: "⚖️ Informations légales",
  footerLinkPrivacy: "🔒 Confidentialité",
  footerLinkConditions: "📄 Conditions d'utilisation",
  footerDisclaimer: "⚠️ Affiliation : Ce site perçoit une commission sur les inscriptions via les liens partenaires, sans coût supplémentaire pour vous. ℹ️ Annuaire vitrine : Aucun contact direct — les profils redirigent vers des plateformes partenaires. 🔞 Réservé aux adultes de 18 ans et plus.",
  footerCopyright: "© {year} {siteName} — Site d'affiliation. Pour adultes 18+.",
  footerBottomLegal: "Légal",
  footerBottomPrivacy: "Confidentialité",
  footerBottomConditions: "Conditions",
  notFoundTitle: "Page introuvable",
  notFoundText: "Ce profil ou cette page n'existe plus. Découvrez d'autres célibataires du Québec.",
  notFoundButton: "❤ Voir les annonces",
  legalTitle: "Informations légales",
  legalIntro: "Transparence complète sur le fonctionnement de ce site.",
  conditionsTitle: "Conditions d'utilisation",
  conditionsIntro: "Dernière mise à jour : février 2025",
  privacyTitle: "Politique de confidentialité",
  privacyIntro: "Dernière mise à jour : février 2025",
}

export type TextKey = keyof typeof DEFAULT_TEXTS
